# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish Win x64
      run: dotnet publish /home/runner/work/entity-explorer/entity-explorer/observe-entity-explorer.csproj -p:PublishProfileFullPath=/home/runner/work/entity-explorer/entity-explorer/Properties/PublisProfiles/win-x64-self-contained.pubxml -o /home/runner/work/entity-explorer/entity-explorer/bin/Publish/win
    - name: Publish OSX x64
      run: dotnet publish -p:PublishProfileFullPath=/home/runner/work/entity-explorer/entity-explorer/Properties/PublisProfiles/osx-x64-self-contained.pubxml  -o /home/runner/work/entity-explorer/entity-explorer/bin/Publish/osx
    - name: Publish OSX ARM
      run: dotnet publish -p:PublishProfile=Properties/PublishProfiles/osx-arm64-self-contained
    - name: Publish Linux x64
      run: dotnet publish -p:PublishProfile=linux-x64-self-contained -p:PublishProfileRootFolder=Properties/PublishProfiles
    - name: View Results
      run: ls /home/runner/work/entity-explorer/entity-explorer/bin/Debug/net7.0/publish/
    - name: View Results
      run: ls /home/runner/work/entity-explorer/entity-explorer/bin/Debug/net7.0/publish/win
    - name: View Results
      run: ls /home/runner/work/entity-explorer/entity-explorer/bin/Debug/net7.0/publish/osx

    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
