# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish Win x64
      #run: dotnet publish /home/runner/work/entity-explorer/entity-explorer/observe-entity-explorer.csproj -p:PublishProfileFullPath=/home/runner/work/entity-explorer/entity-explorer/Properties/PublisProfiles/win-x64-self-contained.pubxml -o /home/runner/work/entity-explorer/entity-explorer/bin/publish/win
      # Using pubxml isn't working in Github runner, using manual overrides
      run: dotnet publish --self-contained --runtime win-x64 -c Debug -p:PublishSingleFile=true -o /home/runner/work/entity-explorer/entity-explorer/bin/publish/win
    - name: Publish OSX x64
      run: dotnet publish --self-contained --runtime osx-x64 -c Debug -p:PublishSingleFile=true -o /home/runner/work/entity-explorer/entity-explorer/bin/publish/osx
    - name: Publish OSX ARM
      run: dotnet publish --self-contained --runtime osx-arm64 -c Debug -p:PublishSingleFile=true -o /home/runner/work/entity-explorer/entity-explorer/bin/publish/osx-arm
    - name: Publish Linux x64
      run: dotnet publish --self-contained --runtime linux-x64 -c Debug -p:PublishSingleFile=true -o /home/runner/work/entity-explorer/entity-explorer/bin/publish/linux
    # - name: Change Dir
    #  run: cd /home/runner/work/entity-explorer/entity-explorer/bin/publish/win
    - name: Install zip utility
      uses: montudor/action-zip@v1    
    - name: Zip Win x64
      run: zip -qq -r /home/runner/work/entity-explorer/entity-explorer/bin/publish/observe-entity-explorer.win.zip *
      working-directory: /home/runner/work/entity-explorer/entity-explorer/bin/publish/win
    - name: Zip OSX x64
      run: zip -qq -r /home/runner/work/entity-explorer/entity-explorer/bin/publish/observe-entity-explorer.osx.zip *
      working-directory: /home/runner/work/entity-explorer/entity-explorer/bin/publish/osx
    - name: Zip OSX ARM
      run: zip -qq -r /home/runner/work/entity-explorer/entity-explorer/bin/publish/observe-entity-explorer.osx-arm.zip *
      working-directory: /home/runner/work/entity-explorer/entity-explorer/bin/publish/osx-arm
    - name: Zip Linux x64
      run: zip -qq -r /home/runner/work/entity-explorer/entity-explorer/bin/publish/observe-entity-explorer.linux.zip *
      working-directory: /home/runner/work/entity-explorer/entity-explorer/bin/publish/linux
    - name: Upload build results
      uses: actions/upload-artifact@v3
      with:
        name: build-results
        path: /home/runner/work/entity-explorer/entity-explorer/bin/publish/observe-entity-explorer.*.zip    
    # - name: View Results
    #   run: ls -l /home/runner/work/entity-explorer/entity-explorer/*
    # - name: View Results
    #   run: ls -l /home/runner/work/entity-explorer/entity-explorer/*/*
    # - name: View Results
    #   run: ls -l /home/runner/work/entity-explorer/entity-explorer/*/*/*
    # - name: View Results
    #   run: ls -l /home/runner/work/entity-explorer/entity-explorer/*/*/*/*
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
